### ISSUE TITLE
Version 0.1.0 expands write_redis_args incorrectly

### ISSUE THREAD

**Issue by Bajix** [clia/redis_serde_json#1]
Version 0.1.0 should be yanked because it expands write_redis_args on ToRedisArgs incorrectly. As this is already fixed on master, this could be released as is.

**Comment by clia** [comment]
Thanks for the reporting! This is not the original crate on the crates.io, but a fork and a fix for it. We can adapt it ourselves.

**Comment by Bajix** [comment]
Ok I re-released this as [derive-redis-json](https://crates.io/crates/derive-redis-json) so that this can actually be used. Crates.io doesn't allow published crates to use any non-published dependency, so simply pointing to git would've blocked usage and I've got things I'd like to release using this.

**Comment by clia** [comment]
Good job!👍

**Comment by Bajix** [comment]
I'm adding in a derive for the below trait to make it easier to go between an xadd BTreeMap and the subsequent StreamId. Anything else you think this could use?

```
pub trait StreamEntry: Send + Sync + Sized + for<'de> Deserialize<'de> + Serialize {
  fn from_stream_id(stream_id: StreamId) -> Result<Self, RedisError>;
  fn into_xadd_map(&self) -> BTreeMap<&'static str, String>;
}
```
